echo "next 0"
mv scene01_JUST/ scene01_ROI_with_QOI/
mv scene03_JUST/ scene03_ROI_with_QOI/
mv scene05_JUST/ scene05_ROI_with_QOI/
mv scene07_JUST/ scene07_ROI_with_QOI/
mv scene09_JUST/ scene09_ROI_with_QOI/
echo "next 1"
mv scene01_AND_PLACES/ scene01_ROI_and_ARRI_with_QOI/
mv scene03_AND_PLACES/ scene03_ROI_and_ARRI_with_QOI/
mv scene05_AND_PLACES/ scene05_ROI_and_ARRI_with_QOI/
mv scene07_AND_PLACES/ scene07_ROI_and_ARRI_with_QOI/
mv scene09_AND_PLACES/ scene09_ROI_and_ARRI_with_QOI/
echo "next 2"
mv scene01_JU-queryAND-ST/ scene01_ROI_with_QOI_and_AQRI/
mv scene03_JU-queryAND-ST/ scene03_ROI_with_QOI_and_AQRI/
mv scene05_JU-queryAND-ST/ scene05_ROI_with_QOI_and_AQRI/
mv scene07_JU-queryAND-ST/ scene07_ROI_with_QOI_and_AQRI/
mv scene09_JU-queryAND-ST/ scene09_ROI_with_QOI_and_AQRI/
echo "next 3"
mv scene01_A-queryAND-ND_PLACES/ scene01_ROI_and_ARRI_with_QOI_and_AQRI/
mv scene03_A-queryAND-ND_PLACES/ scene03_ROI_and_ARRI_with_QOI_and_AQRI/
mv scene05_A-queryAND-ND_PLACES/ scene05_ROI_and_ARRI_with_QOI_and_AQRI/
mv scene07_A-queryAND-ND_PLACES/ scene07_ROI_and_ARRI_with_QOI_and_AQRI/
mv scene09_A-queryAND-ND_PLACES/ scene09_ROI_and_ARRI_with_QOI_and_AQRI/
